#!/usr/bin/env python3
"""Plot an exported constraint-network problem definition.

Input is generated by `export_constraint_network` and contains task/resource
attributes, pair compatibility matrices, and concrete candidate evaluations.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

VIOLATION_COLUMNS = [
    ("skill_violation", "skill"),
    ("capacity_violation", "capacity"),
    ("task_window_violation", "task window"),
    ("resource_window_violation", "resource window"),
    ("distance_violation", "distance"),
    ("forbidden_zone_violation", "forbidden zone"),
    ("risk_violation", "risk"),
]

PAIR_COLUMNS = [
    ("skill_ok", "skill"),
    ("capacity_ok", "capacity"),
    ("time_overlap_ok", "time overlap"),
    ("distance_ok", "distance"),
    ("zone_ok", "zone"),
    ("risk_ok", "risk"),
    ("pair_ok", "all pair constraints"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot exported constraint-network problem definition.")
    parser.add_argument("--input-dir", required=True, help="Directory produced by export_constraint_network.")
    parser.add_argument("--output-dir", default=None, help="Directory for plots. Defaults to <input-dir>/plots.")
    parser.add_argument("--max-candidate-points", type=int, default=5000, help="Max candidate points for scatter plot.")
    parser.add_argument("--show", action="store_true")
    return parser.parse_args()


def load_matrix(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "task_id" in df.columns:
        df = df.set_index("task_id")
    return df


def plot_heatmap(matrix: pd.DataFrame, title: str, output_path: Path) -> Path:
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(10, 6))
    image = ax.imshow(matrix.values, aspect="auto", interpolation="nearest", vmin=0, vmax=1)
    ax.set_title(title)
    ax.set_xlabel("resource")
    ax.set_ylabel("task")
    if matrix.shape[0] <= 40:
        ax.set_yticks(range(matrix.shape[0]))
        ax.set_yticklabels(matrix.index)
    if matrix.shape[1] <= 32:
        ax.set_xticks(range(matrix.shape[1]))
        ax.set_xticklabels([str(c).replace("resource_", "") for c in matrix.columns], rotation=90)
    cbar = fig.colorbar(image, ax=ax)
    cbar.set_ticks([0, 1])
    cbar.set_ticklabels(["no", "yes"])
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    return output_path


def plot_pair_constraint_pass_rates(pair_df: pd.DataFrame, output_path: Path) -> Path:
    import matplotlib.pyplot as plt

    labels = []
    values = []
    for column, label in PAIR_COLUMNS:
        labels.append(label)
        values.append(float(pair_df[column].mean()) if column in pair_df else 0.0)

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(labels, values)
    ax.set_ylim(0.0, 1.0)
    ax.set_ylabel("fraction of task-resource pairs passing")
    ax.set_title("Task-resource pair compatibility by constraint")
    ax.tick_params(axis="x", rotation=25)
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    return output_path


def plot_candidate_scatter(candidates: pd.DataFrame, output_path: Path, max_points: int) -> Path:
    import matplotlib.pyplot as plt

    if len(candidates) > max_points:
        candidates = candidates.sample(n=max_points, random_state=20260529).sort_index()

    valid = candidates[candidates["valid"] == 1]
    invalid = candidates[candidates["valid"] == 0]

    fig, ax = plt.subplots(figsize=(10, 6))
    if not invalid.empty:
        ax.scatter(invalid["resource_id"], invalid["task_id"], s=8, alpha=0.25, label="invalid")
    if not valid.empty:
        ax.scatter(valid["resource_id"], valid["task_id"], s=18, alpha=0.85, marker="x", label="valid")
    ax.set_xlabel("resource")
    ax.set_ylabel("task")
    ax.set_title("Concrete candidate assignments: valid vs invalid")
    ax.grid(True, alpha=0.2)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    return output_path


def plot_violation_reason_counts(candidates: pd.DataFrame, output_path: Path) -> Path:
    import matplotlib.pyplot as plt

    labels = []
    counts = []
    for column, label in VIOLATION_COLUMNS:
        if column in candidates:
            labels.append(label)
            counts.append(int(candidates[column].sum()))

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(labels, counts)
    ax.set_ylabel("candidate count")
    ax.set_title("Candidate violation reasons")
    ax.tick_params(axis="x", rotation=25)
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    return output_path


def plot_time_windows(tasks: pd.DataFrame, resources: pd.DataFrame, output_path: Path, max_rows: int = 24) -> Path:
    import matplotlib.pyplot as plt

    tasks = tasks.head(max_rows)
    resources = resources.head(max_rows)

    fig, ax = plt.subplots(figsize=(11, 6))
    y = 0
    for _, row in tasks.iterrows():
        ax.broken_barh([(row["earliest_start"], row["latest_end"] - row["earliest_start"])], (y - 0.35, 0.7))
        y += 1
    task_end = y
    y += 1
    for _, row in resources.iterrows():
        ax.broken_barh([(row["available_start"], row["available_end"] - row["available_start"])], (y - 0.35, 0.7))
        y += 1

    yticks = list(range(task_end)) + list(range(task_end + 1, y))
    ylabels = [f"T{int(v)}" for v in tasks["task_id"]] + [f"R{int(v)}" for v in resources["resource_id"]]
    ax.set_yticks(yticks)
    ax.set_yticklabels(ylabels)
    ax.set_xlabel("time")
    ax.set_title("Task time windows and resource availability windows")
    ax.grid(True, axis="x", alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    return output_path


def write_report(input_dir: Path, output_dir: Path, metadata: dict, pair_df: pd.DataFrame, candidates: pd.DataFrame) -> Path:
    path = output_dir / "constraint_network_problem_report.md"
    valid_candidates = int(candidates["valid"].sum())
    lines = [
        "# Constraint Network Problem Definition Report",
        "",
        f"Input directory: `{input_dir}`",
        "",
        "## Size",
        "",
        f"- Tasks: {metadata.get('tasks', 'n/a')}",
        f"- Resources: {metadata.get('resources', 'n/a')}",
        f"- Candidate assignments: {metadata.get('candidates', 'n/a')}",
        f"- Task-resource pairs passing all pair-level constraints: {int(pair_df['pair_ok'].sum())} / {len(pair_df)}",
        f"- Concrete candidates valid: {valid_candidates} / {len(candidates)}",
        "",
        "## Pair-level compatibility",
        "",
    ]
    for column, label in PAIR_COLUMNS:
        if column in pair_df:
            lines.append(f"- {label}: {float(pair_df[column].mean()):.3f} pass fraction")
    lines.extend(["", "## Candidate violation reasons", ""])
    for column, label in VIOLATION_COLUMNS:
        if column in candidates:
            lines.append(f"- {label}: {int(candidates[column].sum())}")
    lines.extend([
        "",
        "## How to read this",
        "",
        "The pair-level matrices answer questions like: `can resource B serve task A before candidate-specific timing is considered?`.",
        "The candidate scatter plot answers the more concrete question: `did this generated task/resource/start-time/duration candidate pass?`.",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir) if args.output_dir else input_dir / "plots"
    output_dir.mkdir(parents=True, exist_ok=True)

    metadata = json.loads((input_dir / "metadata.json").read_text(encoding="utf-8"))
    tasks = pd.read_csv(input_dir / "tasks.csv")
    resources = pd.read_csv(input_dir / "resources.csv")
    pair_df = pd.read_csv(input_dir / "pair_compatibility.csv")
    candidates = pd.read_csv(input_dir / "candidate_evaluations.csv")
    skill_matrix = load_matrix(input_dir / "skill_compatibility_matrix.csv")
    pair_matrix = load_matrix(input_dir / "pair_feasibility_matrix.csv")

    outputs = []
    outputs.append(plot_heatmap(skill_matrix, "Skill compatibility: task requires skills resource has", output_dir / "constraint_skill_compatibility_matrix.png"))
    outputs.append(plot_heatmap(pair_matrix, "Pair-level feasibility: A can work with B", output_dir / "constraint_pair_feasibility_matrix.png"))
    outputs.append(plot_pair_constraint_pass_rates(pair_df, output_dir / "constraint_pair_pass_rates.png"))
    outputs.append(plot_candidate_scatter(candidates, output_dir / "constraint_candidate_assignments.png", args.max_candidate_points))
    outputs.append(plot_violation_reason_counts(candidates, output_dir / "constraint_candidate_violation_reasons.png"))
    outputs.append(plot_time_windows(tasks, resources, output_dir / "constraint_time_windows.png"))
    outputs.append(write_report(input_dir, output_dir, metadata, pair_df, candidates))

    for path in outputs:
        print(f"Wrote: {path}")

    if args.show:
        import matplotlib.pyplot as plt
        plt.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
