#!/usr/bin/env python3
"""Plot Graph BFS shape x scale sweep results from JSONL benchmark output.

This script expects rows generated by execute_graph_bfs_all_sweeps_and_analyze.bat.
The benchmark executable reports total measured milliseconds across the requested
repeat count. We normalize every row to average milliseconds per BFS run
(`total_ms / repeat`) before comparing CPU and GPU variants.

In addition to timing plots, this version also plots BFS anatomy metrics emitted
by graph_bfs metadata:

- max_distance: BFS depth / graph diameter from the chosen source
- max_frontier_size: largest number of active nodes in a BFS level
- mean_frontier_edge_visits: average outgoing edge visits per BFS level
- speedup vs frontier work: the key teaching plot for why random graphs can win

Compatibility note:
Older JSONL files may not contain the exact frontier-anatomy fields added in
Phase 3.2.4. For those files, the plotter derives useful fallback estimates
from fields that already existed (`max_distance`, `reached_count`, and
`mean_out_degree`). Exact benchmark-emitted values are preferred whenever they
are present.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean
from typing import Iterable

GRAPH_KIND_ORDER = ["chain", "grid", "layered", "random"]


@dataclass(frozen=True)
class Sample:
    nodes: int
    edges: int
    variant: str
    graph_kind: str
    shape: str
    per_run_ms: float
    total_ms: float
    repeat: int
    max_distance: int | None
    reached_count: int | None
    frontier_level_count: int | None
    max_frontier_size: int | None
    mean_frontier_size: float | None
    reached_edge_visits: int | None
    max_frontier_edge_visits: int | None
    mean_frontier_edge_visits: float | None
    mean_reached_out_degree: float | None
    frontier_width_to_depth: float | None


@dataclass(frozen=True)
class SummaryRow:
    nodes: int
    edges: int
    graph_kind: str
    shape: str
    cpu_ms_per_run: float | None
    gpu_ms_per_run: float | None
    speedup_cpu_over_gpu: float | None
    cpu_samples: int
    gpu_samples: int
    max_distance: int | None
    reached_count: int | None
    frontier_level_count: int | None
    max_frontier_size: int | None
    mean_frontier_size: float | None
    reached_edge_visits: int | None
    max_frontier_edge_visits: int | None
    mean_frontier_edge_visits: float | None
    mean_reached_out_degree: float | None
    frontier_width_to_depth: float | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot CPU/GPU Graph BFS shape x scale sweeps from a JSONL file."
    )
    parser.add_argument(
        "--jsonl",
        required=True,
        help="Input JSONL file generated by execute_graph_bfs_all_sweeps_and_analyze.bat",
    )
    parser.add_argument(
        "--output-dir",
        default="results/graph_bfs_shape_scale_plots",
        help="Directory for PNG plots and CSV summary",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display figures interactively after writing them",
    )
    return parser.parse_args()


def _parse_optional_int(value: object) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _parse_optional_float(value: object) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _derive_frontier_metrics(metadata: dict[str, object], nodes: int, edges: int) -> dict[str, int | float | None]:
    """Return exact frontier metrics when present, otherwise derive safe estimates.

    Phase 3.2.4 added exact metadata such as `mean_frontier_edge_visits`.
    Earlier sweep files do not have those fields, which used to produce empty
    anatomy plots. This fallback keeps old JSONL files useful while still
    preferring exact values whenever the benchmark emits them.

    The fallback estimates are intentionally conservative teaching aids:

    - frontier_level_count ~= max_distance + 1
    - mean_frontier_size ~= reached_count / frontier_level_count
    - reached_edge_visits ~= reached_count * mean_out_degree
    - mean_frontier_edge_visits ~= reached_edge_visits / frontier_level_count

    They are not a replacement for exact frontier instrumentation, but they are
    good enough to explain why high-depth chain/grid runs starve the GPU while
    low-depth wide-frontier random runs expose useful work.
    """

    max_distance = _parse_optional_int(metadata.get("max_distance"))
    reached_count = _parse_optional_int(metadata.get("reached_count"))

    frontier_level_count = _parse_optional_int(metadata.get("frontier_level_count"))
    if frontier_level_count is None and max_distance is not None and max_distance >= 0:
        frontier_level_count = max_distance + 1

    mean_out_degree = _parse_optional_float(metadata.get("mean_reached_out_degree"))
    if mean_out_degree is None:
        mean_out_degree = _parse_optional_float(metadata.get("mean_out_degree"))
    if mean_out_degree is None and nodes > 0:
        mean_out_degree = float(edges) / float(nodes)

    reached_edge_visits = _parse_optional_int(metadata.get("reached_edge_visits"))
    if reached_edge_visits is None and reached_count is not None and mean_out_degree is not None:
        reached_edge_visits = int(round(float(reached_count) * mean_out_degree))

    mean_frontier_size = _parse_optional_float(metadata.get("mean_frontier_size"))
    if (
        mean_frontier_size is None
        and reached_count is not None
        and frontier_level_count is not None
        and frontier_level_count > 0
    ):
        mean_frontier_size = float(reached_count) / float(frontier_level_count)

    mean_frontier_edge_visits = _parse_optional_float(metadata.get("mean_frontier_edge_visits"))
    if (
        mean_frontier_edge_visits is None
        and reached_edge_visits is not None
        and frontier_level_count is not None
        and frontier_level_count > 0
    ):
        mean_frontier_edge_visits = float(reached_edge_visits) / float(frontier_level_count)

    frontier_width_to_depth = _parse_optional_float(metadata.get("frontier_width_to_depth"))
    if (
        frontier_width_to_depth is None
        and mean_frontier_size is not None
        and frontier_level_count is not None
        and frontier_level_count > 0
    ):
        frontier_width_to_depth = mean_frontier_size / float(frontier_level_count)

    return {
        "frontier_level_count": frontier_level_count,
        "max_frontier_size": _parse_optional_int(metadata.get("max_frontier_size")),
        "mean_frontier_size": mean_frontier_size,
        "reached_edge_visits": reached_edge_visits,
        "max_frontier_edge_visits": _parse_optional_int(metadata.get("max_frontier_edge_visits")),
        "mean_frontier_edge_visits": mean_frontier_edge_visits,
        "mean_reached_out_degree": mean_out_degree,
        "frontier_width_to_depth": frontier_width_to_depth,
    }


def load_samples(jsonl_path: Path) -> list[Sample]:
    samples: list[Sample] = []
    with jsonl_path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_number}: {exc}") from exc

            if row.get("benchmark") != "graph_bfs":
                continue
            if not row.get("correct", False):
                continue

            variant = str(row.get("variant", ""))
            if variant not in {"cpu", "gpu"}:
                continue

            metadata = row.get("metadata") or {}
            graph_kind = str(metadata.get("graph_kind", ""))
            if graph_kind == "random_sparse":
                graph_kind = "random"
            if graph_kind not in GRAPH_KIND_ORDER:
                continue

            input_size = row.get("input_size") or {}
            try:
                nodes = int(input_size["nodes"])
                edges = int(input_size["edges"])
                repeat = int(row.get("repeat", 1))
                total_ms = float(row["total_ms"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"Malformed graph_bfs row on line {line_number}: {row}") from exc

            if repeat <= 0:
                raise ValueError(f"Invalid repeat count on line {line_number}: {repeat}")

            frontier_metrics = _derive_frontier_metrics(metadata, nodes, edges)

            samples.append(
                Sample(
                    nodes=nodes,
                    edges=edges,
                    variant=variant,
                    graph_kind=graph_kind,
                    shape=str(metadata.get("shape", "")),
                    per_run_ms=total_ms / repeat,
                    total_ms=total_ms,
                    repeat=repeat,
                    max_distance=_parse_optional_int(metadata.get("max_distance")),
                    reached_count=_parse_optional_int(metadata.get("reached_count")),
                    frontier_level_count=frontier_metrics["frontier_level_count"],
                    max_frontier_size=frontier_metrics["max_frontier_size"],
                    mean_frontier_size=frontier_metrics["mean_frontier_size"],
                    reached_edge_visits=frontier_metrics["reached_edge_visits"],
                    max_frontier_edge_visits=frontier_metrics["max_frontier_edge_visits"],
                    mean_frontier_edge_visits=frontier_metrics["mean_frontier_edge_visits"],
                    mean_reached_out_degree=frontier_metrics["mean_reached_out_degree"],
                    frontier_width_to_depth=frontier_metrics["frontier_width_to_depth"],
                )
            )

    return samples


def summarize(samples: Iterable[Sample]) -> list[SummaryRow]:
    grouped: dict[tuple[int, int, str, str], dict[str, list[Sample]]] = defaultdict(lambda: {"cpu": [], "gpu": []})

    for sample in samples:
        key = (sample.nodes, sample.edges, sample.graph_kind, sample.shape)
        grouped[key][sample.variant].append(sample)

    summary: list[SummaryRow] = []
    for (nodes, edges, graph_kind, shape), variants in grouped.items():
        cpu_samples = variants["cpu"]
        gpu_samples = variants["gpu"]
        cpu_values = [sample.per_run_ms for sample in cpu_samples]
        gpu_values = [sample.per_run_ms for sample in gpu_samples]
        cpu_ms = mean(cpu_values) if cpu_values else None
        gpu_ms = mean(gpu_values) if gpu_values else None

        speedup: float | None = None
        if cpu_ms is not None and gpu_ms is not None and gpu_ms > 0.0:
            speedup = cpu_ms / gpu_ms

        representative = cpu_samples[0] if cpu_samples else (gpu_samples[0] if gpu_samples else None)
        summary.append(
            SummaryRow(
                nodes=nodes,
                edges=edges,
                graph_kind=graph_kind,
                shape=shape,
                cpu_ms_per_run=cpu_ms,
                gpu_ms_per_run=gpu_ms,
                speedup_cpu_over_gpu=speedup,
                cpu_samples=len(cpu_values),
                gpu_samples=len(gpu_values),
                max_distance=None if representative is None else representative.max_distance,
                reached_count=None if representative is None else representative.reached_count,
                frontier_level_count=None if representative is None else representative.frontier_level_count,
                max_frontier_size=None if representative is None else representative.max_frontier_size,
                mean_frontier_size=None if representative is None else representative.mean_frontier_size,
                reached_edge_visits=None if representative is None else representative.reached_edge_visits,
                max_frontier_edge_visits=None if representative is None else representative.max_frontier_edge_visits,
                mean_frontier_edge_visits=None if representative is None else representative.mean_frontier_edge_visits,
                mean_reached_out_degree=None if representative is None else representative.mean_reached_out_degree,
                frontier_width_to_depth=None if representative is None else representative.frontier_width_to_depth,
            )
        )

    summary.sort(key=lambda row: (GRAPH_KIND_ORDER.index(row.graph_kind), row.nodes, row.edges, row.shape))
    return summary


def _fmt_float(value: float | None) -> str:
    return "" if value is None else f"{value:.9f}"


def write_summary_csv(rows: list[SummaryRow], output_dir: Path) -> Path:
    output_path = output_dir / "graph_bfs_shape_scaling_summary.csv"
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "graph_kind",
                "nodes",
                "edges",
                "shape",
                "max_distance",
                "reached_count",
                "frontier_level_count",
                "max_frontier_size",
                "mean_frontier_size",
                "reached_edge_visits",
                "max_frontier_edge_visits",
                "mean_frontier_edge_visits",
                "mean_reached_out_degree",
                "frontier_width_to_depth",
                "cpu_ms_per_run",
                "gpu_ms_per_run",
                "speedup_cpu_over_gpu",
                "cpu_samples",
                "gpu_samples",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.graph_kind,
                    row.nodes,
                    row.edges,
                    row.shape,
                    "" if row.max_distance is None else row.max_distance,
                    "" if row.reached_count is None else row.reached_count,
                    "" if row.frontier_level_count is None else row.frontier_level_count,
                    "" if row.max_frontier_size is None else row.max_frontier_size,
                    _fmt_float(row.mean_frontier_size),
                    "" if row.reached_edge_visits is None else row.reached_edge_visits,
                    "" if row.max_frontier_edge_visits is None else row.max_frontier_edge_visits,
                    _fmt_float(row.mean_frontier_edge_visits),
                    _fmt_float(row.mean_reached_out_degree),
                    _fmt_float(row.frontier_width_to_depth),
                    _fmt_float(row.cpu_ms_per_run),
                    _fmt_float(row.gpu_ms_per_run),
                    _fmt_float(row.speedup_cpu_over_gpu),
                    row.cpu_samples,
                    row.gpu_samples,
                ]
            )
    return output_path


def print_summary(rows: list[SummaryRow]) -> None:
    if not rows:
        print("No graph_bfs rows were available after filtering.")
        return

    print("Graph BFS shape x scale summary (average milliseconds per BFS run)")
    print("kind       nodes        edges         depth    max_frontier    mean_edges/level   CPU ms/run   GPU ms/run   CPU/GPU speedup")
    print("-----------------------------------------------------------------------------------------------------------------------------")
    for row in rows:
        cpu = "n/a" if row.cpu_ms_per_run is None else f"{row.cpu_ms_per_run:10.6f}"
        gpu = "n/a" if row.gpu_ms_per_run is None else f"{row.gpu_ms_per_run:10.6f}"
        speedup = "n/a" if row.speedup_cpu_over_gpu is None else f"{row.speedup_cpu_over_gpu:10.4f}x"
        depth = "n/a" if row.max_distance is None else str(row.max_distance)
        max_frontier = "n/a" if row.max_frontier_size is None else str(row.max_frontier_size)
        mean_edges = "n/a" if row.mean_frontier_edge_visits is None else f"{row.mean_frontier_edge_visits:.1f}"
        print(
            f"{row.graph_kind:<10} {row.nodes:<12d} {row.edges:<13d} {depth:>7} "
            f"{max_frontier:>15} {mean_edges:>17} {cpu:>12} {gpu:>12} {speedup:>18}"
        )

    print("\nPer-shape crossover summary")
    print("kind       first crossover / best observed speedup")
    print("----------------------------------------------------")
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [
            row for row in rows
            if row.graph_kind == graph_kind and row.speedup_cpu_over_gpu is not None
        ]
        if not shape_rows:
            print(f"{graph_kind:<10} no matched CPU/GPU rows")
            continue

        crossover = next((row for row in shape_rows if (row.speedup_cpu_over_gpu or 0.0) >= 1.0), None)
        if crossover is not None:
            print(
                f"{graph_kind:<10} crossover at nodes={crossover.nodes}, edges={crossover.edges}, "
                f"depth={crossover.max_distance}, max_frontier={crossover.max_frontier_size}, "
                f"speedup={crossover.speedup_cpu_over_gpu:.4f}x"
            )
        else:
            best = max(shape_rows, key=lambda row: row.speedup_cpu_over_gpu or -math.inf)
            print(
                f"{graph_kind:<10} no crossover; best={best.speedup_cpu_over_gpu:.4f}x "
                f"at nodes={best.nodes}, edges={best.edges}, depth={best.max_distance}, "
                f"max_frontier={best.max_frontier_size}"
            )


def _paired_rows(rows: list[SummaryRow]) -> list[SummaryRow]:
    return [
        row for row in rows
        if row.cpu_ms_per_run is not None and row.gpu_ms_per_run is not None
    ]


def _plot_metric_by_nodes(plt, paired_rows: list[SummaryRow], output_dir: Path, filename: str, ylabel: str, title: str, getter) -> Path | None:
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    plotted_any = False
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [row for row in paired_rows if row.graph_kind == graph_kind and getter(row) is not None]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.nodes)
        ax.plot([row.nodes for row in shape_rows], [getter(row) for row in shape_rows], marker="o", label=graph_kind)
        plotted_any = True

    if not plotted_any:
        plt.close(fig)
        print(f"Skipping {filename}: no rows contained the required metric.")
        return None

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()
    ax.grid(True, which="both", linestyle=":", linewidth=0.6)
    fig.tight_layout()
    path = output_dir / filename
    fig.savefig(path, dpi=160)
    return path


def plot_rows(rows: list[SummaryRow], output_dir: Path, show: bool) -> list[Path]:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is not installed. Wrote CSV summary only; skipping PNG plots.")
        return []

    paired_rows = _paired_rows(rows)
    if not paired_rows:
        print("No paired CPU/GPU rows are available; skipping PNG plots.")
        return []

    output_paths: list[Path] = []

    # 1) Speedup by graph kind.
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [row for row in paired_rows if row.graph_kind == graph_kind]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.nodes)
        ax.plot([row.nodes for row in shape_rows], [row.speedup_cpu_over_gpu for row in shape_rows], marker="o", label=graph_kind)
    ax.axhline(1.0, linestyle="--", label="CPU/GPU parity")
    ax.set_xscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("CPU time / GPU time")
    ax.set_title("Graph BFS GPU speedup depends on graph anatomy")
    ax.legend()
    ax.grid(True, which="both", linestyle=":", linewidth=0.6)
    fig.tight_layout()
    speedup_path = output_dir / "graph_bfs_shape_scaling_speedup.png"
    fig.savefig(speedup_path, dpi=160)
    output_paths.append(speedup_path)

    def _append_if_written(path: Path | None) -> None:
        if path is not None:
            output_paths.append(path)

    # 2) CPU time by graph kind.
    _append_if_written(_plot_metric_by_nodes(
        plt,
        paired_rows,
        output_dir,
        "graph_bfs_shape_scaling_cpu_times.png",
        "CPU average milliseconds per BFS run",
        "CPU queue BFS time by graph anatomy",
        lambda row: row.cpu_ms_per_run,
    ))

    # 3) GPU time by graph kind.
    _append_if_written(_plot_metric_by_nodes(
        plt,
        paired_rows,
        output_dir,
        "graph_bfs_shape_scaling_gpu_times.png",
        "GPU average milliseconds per BFS run",
        "GPU frontier BFS time by graph anatomy",
        lambda row: row.gpu_ms_per_run,
    ))

    # 4) BFS depth by graph kind.
    _append_if_written(_plot_metric_by_nodes(
        plt,
        paired_rows,
        output_dir,
        "graph_bfs_shape_scaling_depth.png",
        "BFS max distance / depth",
        "BFS depth explains synchronization cost",
        lambda row: row.max_distance,
    ))

    # 5) Max frontier width by graph kind.
    _append_if_written(_plot_metric_by_nodes(
        plt,
        paired_rows,
        output_dir,
        "graph_bfs_shape_scaling_max_frontier.png",
        "Maximum frontier size",
        "Wide frontiers expose useful GPU parallelism",
        lambda row: row.max_frontier_size,
    ))

    # 6) Average edge work per BFS level.
    _append_if_written(_plot_metric_by_nodes(
        plt,
        paired_rows,
        output_dir,
        "graph_bfs_shape_scaling_mean_edges_per_level.png",
        "Mean outgoing edge visits per BFS level",
        "Useful work per synchronization point",
        lambda row: row.mean_frontier_edge_visits,
    ))

    # 7) Speedup vs mean edge work per level.
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    plotted_any = False
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [
            row for row in paired_rows
            if row.graph_kind == graph_kind
            and row.mean_frontier_edge_visits is not None
            and row.speedup_cpu_over_gpu is not None
            and row.mean_frontier_edge_visits > 0
            and row.speedup_cpu_over_gpu > 0
        ]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.mean_frontier_edge_visits or 0.0)
        ax.plot(
            [row.mean_frontier_edge_visits for row in shape_rows],
            [row.speedup_cpu_over_gpu for row in shape_rows],
            marker="o",
            label=graph_kind,
        )
        plotted_any = True

    if plotted_any:
        ax.axhline(1.0, linestyle="--", label="CPU/GPU parity")
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel("Mean outgoing edge visits per BFS level")
        ax.set_ylabel("CPU time / GPU time")
        ax.set_title("GPU BFS improves when there is enough work per frontier level")
        ax.legend()
        ax.grid(True, which="both", linestyle=":", linewidth=0.6)
        fig.tight_layout()
        work_path = output_dir / "graph_bfs_speedup_vs_frontier_work.png"
        fig.savefig(work_path, dpi=160)
        output_paths.append(work_path)
    else:
        plt.close(fig)
        print("Skipping graph_bfs_speedup_vs_frontier_work.png: no frontier-work metric was available.")

    if show:
        plt.show()
    else:
        plt.close("all")

    return output_paths


def main() -> int:
    args = parse_args()
    jsonl_path = Path(args.jsonl)
    if not jsonl_path.exists():
        raise FileNotFoundError(f"JSONL sweep file does not exist: {jsonl_path}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    samples = load_samples(jsonl_path)
    rows = summarize(samples)
    csv_path = write_summary_csv(rows, output_dir)

    if rows and any(row.mean_frontier_edge_visits is not None for row in rows):
        exact_count = sum(1 for sample in samples if sample.mean_frontier_edge_visits is not None)
        print(
            "Frontier-work values are available. "
            "For older JSONL files they may be derived fallback estimates; "
            "rerun the benchmark after Phase 3.2.4 for exact metrics."
        )

    print_summary(rows)
    print(f"\nWrote CSV summary: {csv_path}")

    plot_paths = plot_rows(rows, output_dir, args.show)
    for plot_path in plot_paths:
        print(f"Wrote plot: {plot_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
