#!/usr/bin/env python3
"""Plot delta-width tuning results for graph_weighted_relaxation.

The normal weighted-relaxation sweep uses one fixed delta. This script consumes
JSONL generated by the canonical runner's delta-tuning step and plots the
`gpu-delta-stepping` and `gpu-delta-light-heavy` rows, while also retaining
CPU/global/frontier timings for reference when available.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Row:
    case: str
    delta: int
    variant: str
    ms_per_run: float
    iterations: int | None
    correct: bool


def optional_int(value: object) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def parse_case_and_delta(label: str) -> tuple[str, int] | None:
    match = re.match(r"(.+)_delta(\d+)$", label)
    if not match:
        return None
    return match.group(1), int(match.group(2))


def load_rows(path: Path) -> list[Row]:
    rows: list[Row] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            line = raw.strip()
            if not line:
                continue
            data = json.loads(line)
            if data.get("benchmark") != "graph_weighted_relaxation":
                continue
            parsed = parse_case_and_delta(str(data.get("preset", "")))
            if parsed is None:
                continue
            repeat = int(data.get("repeat", 1))
            if repeat <= 0:
                raise ValueError(f"Invalid repeat on line {line_number}: {repeat}")
            metadata = data.get("metadata") or {}
            rows.append(Row(
                case=parsed[0],
                delta=parsed[1],
                variant=str(data.get("variant", "")),
                ms_per_run=float(data.get("total_ms", 0.0)) / repeat,
                iterations=optional_int(metadata.get("iterations")),
                correct=bool(data.get("correct", False)),
            ))
    return rows


def grouped(rows: list[Row]) -> dict[str, list[Row]]:
    groups: dict[str, list[Row]] = defaultdict(list)
    for row in rows:
        if row.correct:
            groups[row.case].append(row)
    for values in groups.values():
        values.sort(key=lambda r: (r.delta, r.variant))
    return dict(groups)


def write_summary_csv(rows: list[Row], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "graph_weighted_delta_tuning_summary.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["case", "delta", "variant", "ms_per_run", "iterations", "correct"])
        for row in rows:
            writer.writerow([row.case, row.delta, row.variant, row.ms_per_run, row.iterations, row.correct])
    return path


def plot_delta_times(rows: list[Row], output_dir: Path, show: bool) -> list[Path]:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        print(f"matplotlib is not available: {exc}")
        return []

    paths: list[Path] = []
    groups = grouped(rows)
    for case, values in groups.items():
        delta_rows = [r for r in values if r.variant == "gpu-delta-stepping"]
        light_heavy_rows = [r for r in values if r.variant == "gpu-delta-light-heavy"]
        if not delta_rows and not light_heavy_rows:
            continue
        baseline_cpu = [r for r in values if r.variant == "cpu"]
        baseline_global = [r for r in values if r.variant == "gpu"]
        baseline_frontier = [r for r in values if r.variant == "gpu-frontier"]

        fig, ax = plt.subplots(figsize=(9, 5.5))
        if delta_rows:
            ax.plot([r.delta for r in delta_rows], [r.ms_per_run for r in delta_rows], marker="o", label="GPU delta-step")
        if light_heavy_rows:
            ax.plot([r.delta for r in light_heavy_rows], [r.ms_per_run for r in light_heavy_rows], marker="s", label="GPU light/heavy delta")
        if baseline_cpu:
            ax.axhline(baseline_cpu[0].ms_per_run, linestyle="--", linewidth=1, label="CPU Dijkstra")
        if baseline_global:
            ax.axhline(baseline_global[0].ms_per_run, linestyle=":", linewidth=1, label="GPU global")
        if baseline_frontier:
            ax.axhline(baseline_frontier[0].ms_per_run, linestyle="-.", linewidth=1, label="GPU frontier")
        ax.set_xscale("log", base=2)
        ax.set_yscale("log")
        ax.set_xlabel("delta bucket width")
        ax.set_ylabel("average ms per run")
        ax.set_title(f"Weighted relaxation delta tuning: {case}")
        ax.grid(True, which="both", alpha=0.3)
        ax.legend()
        fig.tight_layout()
        path = output_dir / f"graph_wr_delta_tuning_{case}.png"
        fig.savefig(path, dpi=150)
        paths.append(path)

        iter_rows = [r for r in delta_rows if r.iterations is not None]
        light_iter_rows = [r for r in light_heavy_rows if r.iterations is not None]
        if iter_rows or light_iter_rows:
            fig2, ax2 = plt.subplots(figsize=(9, 5.0))
            if iter_rows:
                ax2.plot([r.delta for r in iter_rows], [r.iterations for r in iter_rows], marker="s", label="GPU delta-step")
            if light_iter_rows:
                ax2.plot([r.delta for r in light_iter_rows], [r.iterations for r in light_iter_rows], marker="o", label="GPU light/heavy delta")
            ax2.set_xscale("log", base=2)
            ax2.set_yscale("log")
            ax2.set_xlabel("delta bucket width")
            ax2.set_ylabel("GPU delta iterations")
            ax2.set_title(f"Delta iterations vs bucket width: {case}")
            ax2.grid(True, which="both", alpha=0.3)
            ax2.legend()
            fig2.tight_layout()
            path2 = output_dir / f"graph_wr_delta_tuning_iterations_{case}.png"
            fig2.savefig(path2, dpi=150)
            paths.append(path2)

    if show:
        plt.show()
    return paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot weighted-relaxation delta tuning results.")
    parser.add_argument("--jsonl", required=True)
    parser.add_argument("--output-dir", default="results/graph_weighted_relaxation_delta_tuning_plots")
    parser.add_argument("--show", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = load_rows(Path(args.jsonl))
    if not rows:
        raise SystemExit(f"No delta-tuning rows found in {args.jsonl}")
    output_dir = Path(args.output_dir)
    csv_path = write_summary_csv(rows, output_dir)
    print(f"Wrote delta tuning CSV: {csv_path}")
    for path in plot_delta_times(rows, output_dir, args.show):
        print(f"Wrote plot: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
