#!/usr/bin/env python3
"""Plot Graph BFS layered scale-sweep results from JSONL benchmark output.

The benchmark executable reports total measured milliseconds across the requested
repeat count. This plotter normalizes every row to average milliseconds per BFS
run (`total_ms / repeat`) before comparing CPU and GPU variants.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean
from typing import Iterable


@dataclass(frozen=True)
class Sample:
    nodes: int
    edges: int
    variant: str
    graph_kind: str
    shape: str
    per_run_ms: float
    total_ms: float
    repeat: int


@dataclass(frozen=True)
class SummaryRow:
    nodes: int
    edges: int
    graph_kind: str
    shape: str
    cpu_ms_per_run: float | None
    gpu_ms_per_run: float | None
    speedup_cpu_over_gpu: float | None
    cpu_samples: int
    gpu_samples: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot CPU/GPU Graph BFS scaling from a JSONL sweep file."
    )
    parser.add_argument("--jsonl", required=True, help="Input JSONL file generated by execute_graph_bfs_all_sweeps_and_analyze.bat")
    parser.add_argument(
        "--output-dir",
        default="results/graph_bfs_layered_scale_plots",
        help="Directory for PNG plots and CSV summary",
    )
    parser.add_argument(
        "--graph-kind",
        default="layered",
        help="Graph kind to keep from the JSONL metadata. Default: layered",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display figures interactively after writing them",
    )
    return parser.parse_args()


def load_samples(jsonl_path: Path, graph_kind_filter: str) -> list[Sample]:
    samples: list[Sample] = []
    with jsonl_path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_number}: {exc}") from exc

            if row.get("benchmark") != "graph_bfs":
                continue
            if not row.get("correct", False):
                continue

            variant = str(row.get("variant", ""))
            if variant not in {"cpu", "gpu"}:
                continue

            metadata = row.get("metadata") or {}
            graph_kind = str(metadata.get("graph_kind", ""))
            if graph_kind_filter and graph_kind != graph_kind_filter:
                continue

            input_size = row.get("input_size") or {}
            try:
                nodes = int(input_size["nodes"])
                edges = int(input_size["edges"])
                repeat = int(row.get("repeat", 1))
                total_ms = float(row["total_ms"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"Malformed graph_bfs row on line {line_number}: {row}") from exc

            if repeat <= 0:
                raise ValueError(f"Invalid repeat count on line {line_number}: {repeat}")

            shape = str(metadata.get("shape", ""))
            samples.append(
                Sample(
                    nodes=nodes,
                    edges=edges,
                    variant=variant,
                    graph_kind=graph_kind,
                    shape=shape,
                    per_run_ms=total_ms / repeat,
                    total_ms=total_ms,
                    repeat=repeat,
                )
            )

    return samples


def summarize(samples: Iterable[Sample]) -> list[SummaryRow]:
    grouped: dict[tuple[int, int, str, str], dict[str, list[float]]] = defaultdict(lambda: {"cpu": [], "gpu": []})

    for sample in samples:
        key = (sample.nodes, sample.edges, sample.graph_kind, sample.shape)
        grouped[key][sample.variant].append(sample.per_run_ms)

    summary: list[SummaryRow] = []
    for (nodes, edges, graph_kind, shape), variants in grouped.items():
        cpu_values = variants["cpu"]
        gpu_values = variants["gpu"]
        cpu_ms = mean(cpu_values) if cpu_values else None
        gpu_ms = mean(gpu_values) if gpu_values else None

        speedup: float | None = None
        if cpu_ms is not None and gpu_ms is not None and gpu_ms > 0.0:
            speedup = cpu_ms / gpu_ms

        summary.append(
            SummaryRow(
                nodes=nodes,
                edges=edges,
                graph_kind=graph_kind,
                shape=shape,
                cpu_ms_per_run=cpu_ms,
                gpu_ms_per_run=gpu_ms,
                speedup_cpu_over_gpu=speedup,
                cpu_samples=len(cpu_values),
                gpu_samples=len(gpu_values),
            )
        )

    summary.sort(key=lambda row: (row.nodes, row.edges, row.shape))
    return summary


def write_summary_csv(rows: list[SummaryRow], output_dir: Path) -> Path:
    output_path = output_dir / "graph_bfs_scaling_summary.csv"
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "nodes",
                "edges",
                "graph_kind",
                "shape",
                "cpu_ms_per_run",
                "gpu_ms_per_run",
                "speedup_cpu_over_gpu",
                "cpu_samples",
                "gpu_samples",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.nodes,
                    row.edges,
                    row.graph_kind,
                    row.shape,
                    "" if row.cpu_ms_per_run is None else f"{row.cpu_ms_per_run:.9f}",
                    "" if row.gpu_ms_per_run is None else f"{row.gpu_ms_per_run:.9f}",
                    "" if row.speedup_cpu_over_gpu is None else f"{row.speedup_cpu_over_gpu:.9f}",
                    row.cpu_samples,
                    row.gpu_samples,
                ]
            )
    return output_path


def print_summary(rows: list[SummaryRow]) -> None:
    if not rows:
        print("No graph_bfs rows were available after filtering.")
        return

    print("Graph BFS scaling summary (average milliseconds per BFS run)")
    print("nodes        edges         CPU ms/run   GPU ms/run   CPU/GPU speedup")
    print("------------------------------------------------------------------------")
    for row in rows:
        cpu = "n/a" if row.cpu_ms_per_run is None else f"{row.cpu_ms_per_run:10.6f}"
        gpu = "n/a" if row.gpu_ms_per_run is None else f"{row.gpu_ms_per_run:10.6f}"
        speedup = "n/a" if row.speedup_cpu_over_gpu is None else f"{row.speedup_cpu_over_gpu:10.4f}x"
        print(f"{row.nodes:<12d} {row.edges:<13d} {cpu:>12} {gpu:>12} {speedup:>18}")

    rows_with_speedup = [row for row in rows if row.speedup_cpu_over_gpu is not None]
    if not rows_with_speedup:
        print("\nNo CPU/GPU matched pairs were found, so no speedup crossover can be reported.")
        return

    crossover = next((row for row in rows_with_speedup if row.speedup_cpu_over_gpu is not None and row.speedup_cpu_over_gpu >= 1.0), None)
    if crossover is not None:
        print(
            "\nFirst measured GPU crossover: "
            f"nodes={crossover.nodes}, edges={crossover.edges}, "
            f"speedup={crossover.speedup_cpu_over_gpu:.4f}x"
        )
    else:
        best = max(rows_with_speedup, key=lambda row: row.speedup_cpu_over_gpu or -math.inf)
        print(
            "\nNo GPU crossover observed in this sweep. "
            f"Best measured CPU/GPU speedup was {best.speedup_cpu_over_gpu:.4f}x "
            f"at nodes={best.nodes}, edges={best.edges}."
        )


def plot_rows(rows: list[SummaryRow], output_dir: Path, show: bool) -> list[Path]:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is not installed. Wrote CSV summary only; skipping PNG plots.")
        return []

    paired_rows = [
        row for row in rows
        if row.cpu_ms_per_run is not None and row.gpu_ms_per_run is not None
    ]
    if not paired_rows:
        print("No paired CPU/GPU rows are available; skipping PNG plots.")
        return []

    output_paths: list[Path] = []

    nodes = [row.nodes for row in paired_rows]
    cpu_ms = [row.cpu_ms_per_run for row in paired_rows]
    gpu_ms = [row.gpu_ms_per_run for row in paired_rows]
    speedups = [row.speedup_cpu_over_gpu for row in paired_rows]

    # 1) Scaling time plot.
    fig = plt.figure(figsize=(10, 6))
    ax = fig.add_subplot(111)
    ax.plot(nodes, cpu_ms, marker="o", label="CPU queue BFS")
    ax.plot(nodes, gpu_ms, marker="o", label="GPU frontier BFS")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("Average milliseconds per BFS run")
    ax.set_title("Graph BFS scaling: CPU vs GPU")
    ax.grid(True, which="both", linestyle=":")
    ax.legend()
    fig.tight_layout()
    time_path = output_dir / "graph_bfs_scaling_times.png"
    fig.savefig(time_path, dpi=160)
    output_paths.append(time_path)

    # 2) Speedup plot.
    fig = plt.figure(figsize=(10, 6))
    ax = fig.add_subplot(111)
    ax.plot(nodes, speedups, marker="o", label="CPU time / GPU time")
    ax.axhline(1.0, linestyle="--", label="GPU crossover threshold")
    ax.set_xscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("Speedup (CPU ms/run ÷ GPU ms/run)")
    ax.set_title("Graph BFS GPU crossover study")
    ax.grid(True, which="both", linestyle=":")
    ax.legend()
    fig.tight_layout()
    speedup_path = output_dir / "graph_bfs_scaling_speedup.png"
    fig.savefig(speedup_path, dpi=160)
    output_paths.append(speedup_path)

    if show:
        plt.show()
    else:
        plt.close("all")

    return output_paths


def main() -> int:
    args = parse_args()
    jsonl_path = Path(args.jsonl)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not jsonl_path.exists():
        raise FileNotFoundError(f"JSONL input does not exist: {jsonl_path}")

    samples = load_samples(jsonl_path, args.graph_kind)
    rows = summarize(samples)
    print_summary(rows)

    csv_path = write_summary_csv(rows, output_dir)
    print(f"\nWrote {csv_path}")

    plot_paths = plot_rows(rows, output_dir, args.show)
    for path in plot_paths:
        print(f"Wrote {path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
