#!/usr/bin/env python3
"""Plot Graph BFS shape x scale sweep results from JSONL benchmark output.

This script expects rows generated by execute_graph_bfs_shape_scale_sweep.bat.
The benchmark executable reports total measured milliseconds across the requested
repeat count. We normalize every row to average milliseconds per BFS run
(`total_ms / repeat`) before comparing CPU and GPU variants.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean
from typing import Iterable

GRAPH_KIND_ORDER = ["chain", "grid", "layered", "random"]


@dataclass(frozen=True)
class Sample:
    nodes: int
    edges: int
    variant: str
    graph_kind: str
    shape: str
    per_run_ms: float
    total_ms: float
    repeat: int
    max_distance: int | None
    reached_count: int | None


@dataclass(frozen=True)
class SummaryRow:
    nodes: int
    edges: int
    graph_kind: str
    shape: str
    cpu_ms_per_run: float | None
    gpu_ms_per_run: float | None
    speedup_cpu_over_gpu: float | None
    cpu_samples: int
    gpu_samples: int
    max_distance: int | None
    reached_count: int | None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot CPU/GPU Graph BFS shape x scale sweeps from a JSONL file."
    )
    parser.add_argument(
        "--jsonl",
        required=True,
        help="Input JSONL file generated by execute_graph_bfs_shape_scale_sweep.bat",
    )
    parser.add_argument(
        "--output-dir",
        default="results/graph_bfs_shape_scale_plots",
        help="Directory for PNG plots and CSV summary",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display figures interactively after writing them",
    )
    return parser.parse_args()


def _parse_optional_int(value: object) -> int | None:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def load_samples(jsonl_path: Path) -> list[Sample]:
    samples: list[Sample] = []
    with jsonl_path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_number}: {exc}") from exc

            if row.get("benchmark") != "graph_bfs":
                continue
            if not row.get("correct", False):
                continue

            variant = str(row.get("variant", ""))
            if variant not in {"cpu", "gpu"}:
                continue

            metadata = row.get("metadata") or {}
            graph_kind = str(metadata.get("graph_kind", ""))
            if graph_kind == "random_sparse":
                graph_kind = "random"
            if graph_kind not in GRAPH_KIND_ORDER:
                continue

            input_size = row.get("input_size") or {}
            try:
                nodes = int(input_size["nodes"])
                edges = int(input_size["edges"])
                repeat = int(row.get("repeat", 1))
                total_ms = float(row["total_ms"])
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"Malformed graph_bfs row on line {line_number}: {row}") from exc

            if repeat <= 0:
                raise ValueError(f"Invalid repeat count on line {line_number}: {repeat}")

            samples.append(
                Sample(
                    nodes=nodes,
                    edges=edges,
                    variant=variant,
                    graph_kind=graph_kind,
                    shape=str(metadata.get("shape", "")),
                    per_run_ms=total_ms / repeat,
                    total_ms=total_ms,
                    repeat=repeat,
                    max_distance=_parse_optional_int(metadata.get("max_distance")),
                    reached_count=_parse_optional_int(metadata.get("reached_count")),
                )
            )

    return samples


def summarize(samples: Iterable[Sample]) -> list[SummaryRow]:
    grouped: dict[tuple[int, int, str, str], dict[str, list[Sample]]] = defaultdict(lambda: {"cpu": [], "gpu": []})

    for sample in samples:
        key = (sample.nodes, sample.edges, sample.graph_kind, sample.shape)
        grouped[key][sample.variant].append(sample)

    summary: list[SummaryRow] = []
    for (nodes, edges, graph_kind, shape), variants in grouped.items():
        cpu_samples = variants["cpu"]
        gpu_samples = variants["gpu"]
        cpu_values = [sample.per_run_ms for sample in cpu_samples]
        gpu_values = [sample.per_run_ms for sample in gpu_samples]
        cpu_ms = mean(cpu_values) if cpu_values else None
        gpu_ms = mean(gpu_values) if gpu_values else None

        speedup: float | None = None
        if cpu_ms is not None and gpu_ms is not None and gpu_ms > 0.0:
            speedup = cpu_ms / gpu_ms

        representative = cpu_samples[0] if cpu_samples else (gpu_samples[0] if gpu_samples else None)
        summary.append(
            SummaryRow(
                nodes=nodes,
                edges=edges,
                graph_kind=graph_kind,
                shape=shape,
                cpu_ms_per_run=cpu_ms,
                gpu_ms_per_run=gpu_ms,
                speedup_cpu_over_gpu=speedup,
                cpu_samples=len(cpu_values),
                gpu_samples=len(gpu_values),
                max_distance=None if representative is None else representative.max_distance,
                reached_count=None if representative is None else representative.reached_count,
            )
        )

    summary.sort(key=lambda row: (GRAPH_KIND_ORDER.index(row.graph_kind), row.nodes, row.edges, row.shape))
    return summary


def write_summary_csv(rows: list[SummaryRow], output_dir: Path) -> Path:
    output_path = output_dir / "graph_bfs_shape_scaling_summary.csv"
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "graph_kind",
                "nodes",
                "edges",
                "shape",
                "max_distance",
                "reached_count",
                "cpu_ms_per_run",
                "gpu_ms_per_run",
                "speedup_cpu_over_gpu",
                "cpu_samples",
                "gpu_samples",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.graph_kind,
                    row.nodes,
                    row.edges,
                    row.shape,
                    "" if row.max_distance is None else row.max_distance,
                    "" if row.reached_count is None else row.reached_count,
                    "" if row.cpu_ms_per_run is None else f"{row.cpu_ms_per_run:.9f}",
                    "" if row.gpu_ms_per_run is None else f"{row.gpu_ms_per_run:.9f}",
                    "" if row.speedup_cpu_over_gpu is None else f"{row.speedup_cpu_over_gpu:.9f}",
                    row.cpu_samples,
                    row.gpu_samples,
                ]
            )
    return output_path


def print_summary(rows: list[SummaryRow]) -> None:
    if not rows:
        print("No graph_bfs rows were available after filtering.")
        return

    print("Graph BFS shape x scale summary (average milliseconds per BFS run)")
    print("kind       nodes        edges         depth    CPU ms/run   GPU ms/run   CPU/GPU speedup")
    print("--------------------------------------------------------------------------------------------")
    for row in rows:
        cpu = "n/a" if row.cpu_ms_per_run is None else f"{row.cpu_ms_per_run:10.6f}"
        gpu = "n/a" if row.gpu_ms_per_run is None else f"{row.gpu_ms_per_run:10.6f}"
        speedup = "n/a" if row.speedup_cpu_over_gpu is None else f"{row.speedup_cpu_over_gpu:10.4f}x"
        depth = "n/a" if row.max_distance is None else str(row.max_distance)
        print(f"{row.graph_kind:<10} {row.nodes:<12d} {row.edges:<13d} {depth:>7} {cpu:>12} {gpu:>12} {speedup:>18}")

    print("\nPer-shape crossover summary")
    print("kind       first crossover / best observed speedup")
    print("----------------------------------------------------")
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [
            row for row in rows
            if row.graph_kind == graph_kind and row.speedup_cpu_over_gpu is not None
        ]
        if not shape_rows:
            print(f"{graph_kind:<10} no matched CPU/GPU rows")
            continue

        crossover = next((row for row in shape_rows if (row.speedup_cpu_over_gpu or 0.0) >= 1.0), None)
        if crossover is not None:
            print(
                f"{graph_kind:<10} crossover at nodes={crossover.nodes}, edges={crossover.edges}, "
                f"speedup={crossover.speedup_cpu_over_gpu:.4f}x"
            )
        else:
            best = max(shape_rows, key=lambda row: row.speedup_cpu_over_gpu or -math.inf)
            print(
                f"{graph_kind:<10} no crossover; best={best.speedup_cpu_over_gpu:.4f}x "
                f"at nodes={best.nodes}, edges={best.edges}"
            )


def _paired_rows(rows: list[SummaryRow]) -> list[SummaryRow]:
    return [
        row for row in rows
        if row.cpu_ms_per_run is not None and row.gpu_ms_per_run is not None
    ]


def plot_rows(rows: list[SummaryRow], output_dir: Path, show: bool) -> list[Path]:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is not installed. Wrote CSV summary only; skipping PNG plots.")
        return []

    paired_rows = _paired_rows(rows)
    if not paired_rows:
        print("No paired CPU/GPU rows are available; skipping PNG plots.")
        return []

    output_paths: list[Path] = []

    # 1) Speedup by graph kind.
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [row for row in paired_rows if row.graph_kind == graph_kind]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.nodes)
        ax.plot(
            [row.nodes for row in shape_rows],
            [row.speedup_cpu_over_gpu for row in shape_rows],
            marker="o",
            label=graph_kind,
        )
    ax.axhline(1.0, linestyle="--", label="CPU/GPU parity")
    ax.set_xscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("CPU time / GPU time")
    ax.set_title("Graph BFS GPU speedup depends on graph anatomy")
    ax.legend()
    ax.grid(True, which="both", linestyle=":", linewidth=0.6)
    fig.tight_layout()
    speedup_path = output_dir / "graph_bfs_shape_scaling_speedup.png"
    fig.savefig(speedup_path, dpi=160)
    output_paths.append(speedup_path)

    # 2) CPU time by graph kind.
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [row for row in paired_rows if row.graph_kind == graph_kind]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.nodes)
        ax.plot(
            [row.nodes for row in shape_rows],
            [row.cpu_ms_per_run for row in shape_rows],
            marker="o",
            label=graph_kind,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("CPU average milliseconds per BFS run")
    ax.set_title("CPU queue BFS time by graph anatomy")
    ax.legend()
    ax.grid(True, which="both", linestyle=":", linewidth=0.6)
    fig.tight_layout()
    cpu_path = output_dir / "graph_bfs_shape_scaling_cpu_times.png"
    fig.savefig(cpu_path, dpi=160)
    output_paths.append(cpu_path)

    # 3) GPU time by graph kind.
    fig = plt.figure(figsize=(11, 6.5))
    ax = fig.add_subplot(111)
    for graph_kind in GRAPH_KIND_ORDER:
        shape_rows = [row for row in paired_rows if row.graph_kind == graph_kind]
        if not shape_rows:
            continue
        shape_rows.sort(key=lambda row: row.nodes)
        ax.plot(
            [row.nodes for row in shape_rows],
            [row.gpu_ms_per_run for row in shape_rows],
            marker="o",
            label=graph_kind,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Graph nodes")
    ax.set_ylabel("GPU average milliseconds per BFS run")
    ax.set_title("GPU frontier BFS time by graph anatomy")
    ax.legend()
    ax.grid(True, which="both", linestyle=":", linewidth=0.6)
    fig.tight_layout()
    gpu_path = output_dir / "graph_bfs_shape_scaling_gpu_times.png"
    fig.savefig(gpu_path, dpi=160)
    output_paths.append(gpu_path)

    if show:
        plt.show()
    else:
        plt.close("all")

    return output_paths


def main() -> int:
    args = parse_args()
    jsonl_path = Path(args.jsonl)
    if not jsonl_path.exists():
        raise FileNotFoundError(f"JSONL sweep file does not exist: {jsonl_path}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    samples = load_samples(jsonl_path)
    rows = summarize(samples)
    csv_path = write_summary_csv(rows, output_dir)
    print_summary(rows)
    print(f"\nWrote CSV summary: {csv_path}")

    plot_paths = plot_rows(rows, output_dir, args.show)
    for plot_path in plot_paths:
        print(f"Wrote plot: {plot_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
